# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Piki's blog
email: dev.piki@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  HTML, CSS, Javascript, Web Developer. 
  jekyll 3.8.5. 
  minima theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devpiki.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dev_piki
github_username: devpiki
facebook_username: dev.piko
encoding: 'utf-8'
google_fonts: "Nanum+Gothic:400,700"
search: true # Enable the search feature
lang: 'ko'
author: Piki

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-category-pages
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Post navigation
#post_navigation: true

# Configure the plugin here
category_path: "category" # <- default value
category_layout: "category.html" # <- default value

# PAGINATION
#paginate: 5
#paginate_path: "/blog/page:num/"

pagination:
  enabled: true
  per_page: 5
  limit: 0
  sort_field: "date"
  sort_reverse: true


#tag_dir: tag/
layouts_dir: _layouts

str_search_no_results: "존재하지 않습니다."

disqus:
  shortname: devpiki

#에러 로그 관련 설정
liquid:
  error_mode:       warn
  strict_filters:   true
  strict_variables: false


minima:
  date_format: "%b %-d, %Y"


google_analytics: UA-137162245-1